### ISSUE TITLE
Sidebar menu nested options support

### ISSUE THREAD

**Issue by AdrianRaFo** [47deg/helios#97]
I tried to this on the `sidebar.yml`:
```
  - title: Integrations
    
    nested_options:

      - title: Retrofit
        url: /docs/integrations/retrofit/
```
but it didn't work. I looked into the Arrow repo and that should be fine. Any clue @calvellido?
